---
title: "expolore cricketdata package"
output: html_document
date: "2024-05-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Play around with the "cricketdata" package and explore it a bit.
Package mainly handles download of cricket data from ESPN Crickinfo and Cricsheet.

```{r, message=F}
library(cricketdata)
library(tidyverse)
```

```{r}
# get the codes used in the cricsheet data
cs_codes <- cricsheet_codes
```

```{r, fig.width=10, fig.height=7}
# get some data from cricsheet
ex <- fetch_cricsheet(type="bbb",
                gender="male",
                competition="ipl") |>
  filter(batting_team == "Kolkata Knight Riders") |>
  filter(season == "2023")

# make a silly plot
ggplot(ex, aes(x=ball, y=over, colour=factor(runs_off_bat))) +
  geom_point(position=position_jitter(width = .3, height = .3), size = .9, alpha = 1) +
  scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9)) +
  facet_wrap(~bowling_team, scales = "free") + # scales = free for x axis on each plot
  theme_minimal() +
  theme(axis.line = element_line(linewidth=.25),
        axis.title = element_text(),
        plot.title = element_text(hjust=.5)) +
  xlab("Runs off the bat") + ylab("Over") +
  ggtitle("Runs off the bat per ball every over for Kolkata Knightriders") +
  guides(col = guide_legend(title = "Runs off the bat"))
  
```

```{r}
# try pulling some player stats

find_player_id("Cummins")
# cummins id 489889

pc <- fetch_player_data(489889,
                  matchtype = "test",
                  activity = "bowling")

# vector of aussie grounds
aus_grnds <- c("Sydney", "Melbourne", "Perth", "Brisbane", "Adelaide", "Canberra", "Hobart")

pc_av <- pc |>
  filter(Overs != "DNB") |>
  group_by(Date, Ground, Opposition) |>
  mutate(Overs = as.numeric(Overs),
         Mdns = as.numeric(Mdns),
         Wkts = as.numeric(Wkts),
         Econ = as.numeric(Econ)) |>
  summarise(total_overs = sum(Overs),
            total_mdns = sum(Mdns),
            total_runs = sum(Runs),
            total_wkts = sum(Wkts),
            avg_econ = mean(Econ)) |>
  mutate(Home = ifelse(Ground %in% aus_grnds, "Yes", "No"))

# try some plots
ggplot(pc_av, aes(x=avg_econ, y=total_overs)) +
  geom_point(aes(colour=Home), position=position_jitter(width=.5, height=.5), alpha=.5) +
  scale_y_continuous(labels = scales::label_number()) +
  scale_x_continuous(labels = scales::label_number(accuracy = 1)) +
  geom_smooth(method="lm")
  

```

